### ISSUE TITLE
matched 0 times with 'div#list-right'

### ISSUE THREAD

**Issue by vklymchuk** [jbbarth/redmine_reminders#4]
Hi
Cannot get it work. I can create, edit, give permissions but reminder doesn't show on any page.
All actions in Admin role but I checked non-admin user too.
There are no errors in the log file, except these lines:

Processing by MyController#page as HTML
  Current user: user (id=1)
[1;32mDeface: [ERROR][0m The original source for 'add-refresh-link-to-my-page' has changed, this override should be reviewed to ensure it's still valid.
[1;32mDeface: [ERROR][0m The original source for 'add-new-reminder-link-to-my-page' has changed, this override should be reviewed to ensure it's still valid.
[1;32mDeface:[0m 'add-visible-reminders-on-my-page' matched 0 times with 'div#list-right'
  Rendering my/page.html.erb within layouts/base
  Rendered queries/_columns.html.erb (7.9ms)
  Rendered issues/_list.html.erb (200.6ms)
  Rendered my/blocks/_issues.erb (247.9ms)
  Rendered queries/_columns.html.erb (4.3ms)
  Rendered issues/_list.html.erb (7.0ms)
  Rendered my/blocks/_issues.erb (22.4ms)
  Rendered my/page.html.erb within layouts/base (987.4ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (86.2ms)
  Rendered plugins/global_roles/app/views/hooks/global_roles/_head.html.erb (1.4ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_view_layouts_base_body_top.html.erb (11.6ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_sidebar.html.erb (0.7ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_recent_projects.html.erb (9.5ms)
  Rendered plugins/global_roles/app/views/hooks/global_roles/_view_layouts_base_body_bottom.html.erb (0.8ms)
Completed 200 OK in 1379ms (Views: 1214.2ms | ActiveRecord: 47.2ms)

Why it cannot find the div I don't understand. On the picture you can see that div
![image](https://user-images.githubusercontent.com/68416729/87967403-6b8e1e00-cac7-11ea-8a9f-6d97e6ac5402.png)

Environment:
  Redmine version                4.0.5.stable
  Ruby version                     2.5.7-p206 (2019-10-01) [x86_64-linux]
  Rails version                      5.2.3

  redmine_base_deface        1.5.3
  redmine_notified               0.0.1
  redmine_refresh                0.2.0
  redmine_reminders           0.0.2

Also redmine_notified doesn't show recipients. Only empty form with a ticket number when I click on the link

**Comment by nanego** [comment]
Just fixed this issue.
Can you please try again with the new version?

**Comment by vklymchuk** [comment]
Yes, it works now, thanks.
There is Reminders module setting in the project's settings. It's not implemented yet?
I'll create new issue for redmine_notified. Can you take a look please?

**Comment by nanego** [comment]
As the reminders are only displayed on "my-page" (outside any project), activating the reminders' module for a project does not change anything. The only purpose of this module is to group related permissions in admin area.
